---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contiv-netplugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contiv-netplugin
subjects:
- kind: ServiceAccount
  name: contiv-netplugin
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contiv-netplugin
  namespace: kube-system
rules:
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch 
  - apiGroups:
    - ""
    - extensions
    resources:
      - endpoints
      - nodes
      - namespaces
      - pods
      - services
    verbs:
      - watch
      - list
      - update
      - get

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: contiv-netplugin
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contiv-netmaster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contiv-netmaster
subjects:
- kind: ServiceAccount
  name: contiv-netmaster
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contiv-netmaster
  namespace: kube-system
rules:
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch 
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - watch
      - list
      - update


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: contiv-netmaster
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: contiv-config
  namespace: kube-system
data:
  contiv_mode: kubernetes
  contiv_fwdmode: bridge 
  etcd_cafile : /var/contiv/etcd/etcd-ca.pem
  etcd_certfile : /var/contiv/etcd/etcd.pem
  etcd_keyfile : /var/contiv/etcd/etcd-key.pem
  vlan_if: eth1
  contiv_netmode: vlan
  contiv_etcd: "https://10.43.1.62:2379,https://10.43.1.63:2379,https://10.43.1.64:2379"
  contiv_cni_config: |-
    {
      "cniVersion": "0.1.0",
      "name": "contiv-net",
      "type": "contivk8s"
    }
  contiv_k8s_config: |-
    {
       "K8S_API_SERVER": "https://10.24.247.244:6443",
       "K8S_CA": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
       "K8S_KEY": "",
       "K8S_CERT": "",
       "K8S_TOKEN": "",
       "SVC_SUBNET": "10.96.0.0/12"
    }
