# This manifest deploys the Contiv API Server on Kubernetes.
apiVersion: extensions/v1beta1
kind: DaemonSet 
metadata:
  name: contiv-netmaster
  namespace: kube-system
  labels:
    k8s-app: contiv-netmaster
spec:
  # The netmaster should have 1, 3, 5 nodes of which one is active at any given time.
  # More nodes are desired in a production environment for HA.
  #replicas: 1
  template:
    metadata:
      name: contiv-netmaster
      namespace: kube-system
      labels:
        k8s-app: contiv-netmaster
    spec:
      # The netmaster must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: contiv-netmaster
      containers:
        - name: netmaster-exporter
          image: contiv/stats
          env:
            - name: CONTIV_ETCD
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_etcd
            - name: EXPORTER_MODE
              value: 'netmaster'
        - name: contiv-netmaster
          image: lcb:dev 
          env:
            - name: CONTIV_ROLE
              value: netmaster
            - name: CONTIV_NETMASTER_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_mode
            - name: CONTIV_NETMASTER_ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_etcd
            - name: CONTIV_NETMASTER_ETCD_TLS_KEY 
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: etcd_keyfile
            - name: CONTIV_NETMASTER_ETCD_TLS_CERT 
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: etcd_certfile
            - name: CONTIV_NETMASTER_ETCD_TLS_CA
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: etcd_cafile
            - name: CONTIV_K8S_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_k8s_config
            - name: CONTIV_NETMASTER_FORWARD_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_fwdmode
            - name: CONTIV_NETMASTER_NET_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_netmode
          volumeMounts:
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
            - mountPath: /var/log/contiv
              name: var-log-contiv
              readOnly: false

        - name: contiv-api-proxy
          #image: contiv/auth_proxy:1.2.0
          image: lcb:1.20
          args:
            - --tls-key-file=/var/contiv/auth_proxy_key.pem
            - --tls-certificate=/var/contiv/auth_proxy_cert.pem
            - --data-store-cert=/var/contiv/etcd/etcd.pem
            - --data-store-key=/var/contiv/etcd/etcd-key.pem
            - --data-store-ca=/var/contiv/etcd/etcd-ca.pem
            - --data-store-address=$(STORE_URL)
            - --data-store-driver=$(STORE_DRIVER)
            - --netmaster-address=127.0.0.1:9999
          env:
            - name: NO_NETMASTER_STARTUP_CHECK
              value: "0"
            - name: STORE_URL
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_etcd
            - name: STORE_DRIVER
              value: etcd
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
      volumes:
        # Used by contiv-netmaster
        - name: var-contiv
          hostPath:
            path: /var/contiv
        - name: var-log-contiv
          hostPath:
            path: /var/log/contiv
